//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.24 at 12:06:48 PM PDT 
//


package com.salesforce.metadata;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ActionOverrideType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ActionOverrideType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Default"/>
 *     &lt;enumeration value="Standard"/>
 *     &lt;enumeration value="Scontrol"/>
 *     &lt;enumeration value="Visualforce"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ActionOverrideType")
@XmlEnum
public enum ActionOverrideType {

    @XmlEnumValue("Default")
    DEFAULT("Default"),
    @XmlEnumValue("Standard")
    STANDARD("Standard"),
    @XmlEnumValue("Scontrol")
    SCONTROL("Scontrol"),
    @XmlEnumValue("Visualforce")
    VISUALFORCE("Visualforce");
    private final String value;

    ActionOverrideType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ActionOverrideType fromValue(String v) {
        for (ActionOverrideType c: ActionOverrideType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
