//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.24 at 12:06:48 PM PDT 
//


package com.salesforce.metadata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ZipFile" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/>
 *         &lt;element name="DeployOptions" type="{}DeployOptions"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "zipFile",
    "deployOptions"
})
@XmlRootElement(name = "deploy")
public class Deploy {

    @XmlElement(name = "ZipFile", required = true)
    protected byte[] zipFile;
    @XmlElement(name = "DeployOptions", required = true)
    protected DeployOptions deployOptions;

    /**
     * Gets the value of the zipFile property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getZipFile() {
        return zipFile;
    }

    /**
     * Sets the value of the zipFile property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setZipFile(byte[] value) {
        this.zipFile = ((byte[]) value);
    }

    /**
     * Gets the value of the deployOptions property.
     * 
     * @return
     *     possible object is
     *     {@link DeployOptions }
     *     
     */
    public DeployOptions getDeployOptions() {
        return deployOptions;
    }

    /**
     * Sets the value of the deployOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeployOptions }
     *     
     */
    public void setDeployOptions(DeployOptions value) {
        this.deployOptions = value;
    }

}
