//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.24 at 12:06:48 PM PDT 
//


package com.salesforce.metadata;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Expiration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Expiration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ThirtyDays"/>
 *     &lt;enumeration value="SixtyDays"/>
 *     &lt;enumeration value="NinetyDays"/>
 *     &lt;enumeration value="SixMonths"/>
 *     &lt;enumeration value="OneYear"/>
 *     &lt;enumeration value="Never"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Expiration")
@XmlEnum
public enum Expiration {

    @XmlEnumValue("ThirtyDays")
    THIRTY_DAYS("ThirtyDays"),
    @XmlEnumValue("SixtyDays")
    SIXTY_DAYS("SixtyDays"),
    @XmlEnumValue("NinetyDays")
    NINETY_DAYS("NinetyDays"),
    @XmlEnumValue("SixMonths")
    SIX_MONTHS("SixMonths"),
    @XmlEnumValue("OneYear")
    ONE_YEAR("OneYear"),
    @XmlEnumValue("Never")
    NEVER("Never");
    private final String value;

    Expiration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Expiration fromValue(String v) {
        for (Expiration c: Expiration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
