//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.24 at 12:06:48 PM PDT 
//


package com.salesforce.metadata;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FilterScope.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FilterScope">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Everything"/>
 *     &lt;enumeration value="Mine"/>
 *     &lt;enumeration value="Queue"/>
 *     &lt;enumeration value="Delegated"/>
 *     &lt;enumeration value="MyTerritory"/>
 *     &lt;enumeration value="MyTeamTerritory"/>
 *     &lt;enumeration value="Team"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FilterScope")
@XmlEnum
public enum FilterScope {

    @XmlEnumValue("Everything")
    EVERYTHING("Everything"),
    @XmlEnumValue("Mine")
    MINE("Mine"),
    @XmlEnumValue("Queue")
    QUEUE("Queue"),
    @XmlEnumValue("Delegated")
    DELEGATED("Delegated"),
    @XmlEnumValue("MyTerritory")
    MY_TERRITORY("MyTerritory"),
    @XmlEnumValue("MyTeamTerritory")
    MY_TEAM_TERRITORY("MyTeamTerritory"),
    @XmlEnumValue("Team")
    TEAM("Team");
    private final String value;

    FilterScope(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FilterScope fromValue(String v) {
        for (FilterScope c: FilterScope.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
