//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.24 at 12:06:48 PM PDT 
//


package com.salesforce.metadata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Metadata complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Metadata">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fullName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Metadata", propOrder = {
    "fullName"
})
@XmlSeeAlso({
    WorkflowRule.class,
    CustomDataType.class,
    RecordType.class,
    Profile.class,
    Layout.class,
    WebLink.class,
    AnalyticSnapshot.class,
    CustomSite.class,
    ReportType.class,
    CustomPageWebLink.class,
    Workflow.class,
    SecuritySettings.class,
    Queue.class,
    NamedFilter.class,
    CustomField.class,
    BusinessProcess.class,
    Flow.class,
    PermissionSet.class,
    Report.class,
    ListView.class,
    Package.class,
    CustomApplicationComponent.class,
    FieldSet.class,
    CustomLabel.class,
    Portal.class,
    RoleOrTerritory.class,
    Group.class,
    DataCategoryGroup.class,
    ValidationRule.class,
    HomePageLayout.class,
    Dashboard.class,
    EntitlementTemplate.class,
    CustomObject.class,
    Translations.class,
    CustomLabels.class,
    RemoteSiteSetting.class,
    PicklistValue.class,
    WorkflowAction.class,
    CustomTab.class,
    Letterhead.class,
    SharingReason.class,
    CustomObjectTranslation.class,
    CustomApplication.class,
    MetadataWithContent.class,
    Folder.class,
    BaseSharingRule.class,
    HomePageComponent.class,
    SharingRules.class
})
public class Metadata {

    protected String fullName;

    /**
     * Gets the value of the fullName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * Sets the value of the fullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullName(String value) {
        this.fullName = value;
    }

}
