//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.24 at 12:06:48 PM PDT 
//


package com.salesforce.metadata;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PageComponentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PageComponentType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="links"/>
 *     &lt;enumeration value="htmlArea"/>
 *     &lt;enumeration value="imageOrNote"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PageComponentType")
@XmlEnum
public enum PageComponentType {

    @XmlEnumValue("links")
    LINKS("links"),
    @XmlEnumValue("htmlArea")
    HTML_AREA("htmlArea"),
    @XmlEnumValue("imageOrNote")
    IMAGE_OR_NOTE("imageOrNote");
    private final String value;

    PageComponentType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PageComponentType fromValue(String v) {
        for (PageComponentType c: PageComponentType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
