//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.24 at 12:06:48 PM PDT 
//


package com.salesforce.metadata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PermissionSetObjectPermissions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PermissionSetObjectPermissions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="allowCreate" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="allowDelete" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="allowEdit" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="allowRead" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="modifyAllRecords" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="object" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="viewAllRecords" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PermissionSetObjectPermissions", propOrder = {
    "allowCreate",
    "allowDelete",
    "allowEdit",
    "allowRead",
    "modifyAllRecords",
    "object",
    "viewAllRecords"
})
public class PermissionSetObjectPermissions {

    protected boolean allowCreate;
    protected boolean allowDelete;
    protected boolean allowEdit;
    protected boolean allowRead;
    protected boolean modifyAllRecords;
    @XmlElement(required = true)
    protected String object;
    protected boolean viewAllRecords;

    /**
     * Gets the value of the allowCreate property.
     * 
     */
    public boolean isAllowCreate() {
        return allowCreate;
    }

    /**
     * Sets the value of the allowCreate property.
     * 
     */
    public void setAllowCreate(boolean value) {
        this.allowCreate = value;
    }

    /**
     * Gets the value of the allowDelete property.
     * 
     */
    public boolean isAllowDelete() {
        return allowDelete;
    }

    /**
     * Sets the value of the allowDelete property.
     * 
     */
    public void setAllowDelete(boolean value) {
        this.allowDelete = value;
    }

    /**
     * Gets the value of the allowEdit property.
     * 
     */
    public boolean isAllowEdit() {
        return allowEdit;
    }

    /**
     * Sets the value of the allowEdit property.
     * 
     */
    public void setAllowEdit(boolean value) {
        this.allowEdit = value;
    }

    /**
     * Gets the value of the allowRead property.
     * 
     */
    public boolean isAllowRead() {
        return allowRead;
    }

    /**
     * Sets the value of the allowRead property.
     * 
     */
    public void setAllowRead(boolean value) {
        this.allowRead = value;
    }

    /**
     * Gets the value of the modifyAllRecords property.
     * 
     */
    public boolean isModifyAllRecords() {
        return modifyAllRecords;
    }

    /**
     * Sets the value of the modifyAllRecords property.
     * 
     */
    public void setModifyAllRecords(boolean value) {
        this.modifyAllRecords = value;
    }

    /**
     * Gets the value of the object property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObject() {
        return object;
    }

    /**
     * Sets the value of the object property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObject(String value) {
        this.object = value;
    }

    /**
     * Gets the value of the viewAllRecords property.
     * 
     */
    public boolean isViewAllRecords() {
        return viewAllRecords;
    }

    /**
     * Sets the value of the viewAllRecords property.
     * 
     */
    public void setViewAllRecords(boolean value) {
        this.viewAllRecords = value;
    }

}
