//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.24 at 12:06:48 PM PDT 
//


package com.salesforce.metadata;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReportJobSourceTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ReportJobSourceTypes">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="tabular"/>
 *     &lt;enumeration value="summary"/>
 *     &lt;enumeration value="snapshot"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ReportJobSourceTypes")
@XmlEnum
public enum ReportJobSourceTypes {

    @XmlEnumValue("tabular")
    TABULAR("tabular"),
    @XmlEnumValue("summary")
    SUMMARY("summary"),
    @XmlEnumValue("snapshot")
    SNAPSHOT("snapshot");
    private final String value;

    ReportJobSourceTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ReportJobSourceTypes fromValue(String v) {
        for (ReportJobSourceTypes c: ReportJobSourceTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
