//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.24 at 12:06:48 PM PDT 
//


package com.salesforce.metadata;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReportType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReportType">
 *   &lt;complexContent>
 *     &lt;extension base="{}Metadata">
 *       &lt;sequence>
 *         &lt;element name="baseObject" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="category" type="{}ReportTypeCategory"/>
 *         &lt;element name="deployed" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="join" type="{}ObjectRelationship" minOccurs="0"/>
 *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sections" type="{}ReportLayoutSection" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

@XmlRootElement(name="ReportType")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReportType", propOrder = {
    "baseObject",
    "category",
    "deployed",
    "description",
    "join",
    "label",
    "sections"
})
public class ReportType
    extends Metadata
{

    @XmlElement(required = true)
    protected String baseObject;
    @XmlElement(required = true)
    protected ReportTypeCategory category;
    protected boolean deployed;
    protected String description;
    protected ObjectRelationship join;
    @XmlElement(required = true)
    protected String label;
    protected List<ReportLayoutSection> sections;

    /**
     * Gets the value of the baseObject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseObject() {
        return baseObject;
    }

    /**
     * Sets the value of the baseObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseObject(String value) {
        this.baseObject = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link ReportTypeCategory }
     *     
     */
    public ReportTypeCategory getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportTypeCategory }
     *     
     */
    public void setCategory(ReportTypeCategory value) {
        this.category = value;
    }

    /**
     * Gets the value of the deployed property.
     * 
     */
    public boolean isDeployed() {
        return deployed;
    }

    /**
     * Sets the value of the deployed property.
     * 
     */
    public void setDeployed(boolean value) {
        this.deployed = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the join property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectRelationship }
     *     
     */
    public ObjectRelationship getJoin() {
        return join;
    }

    /**
     * Sets the value of the join property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectRelationship }
     *     
     */
    public void setJoin(ObjectRelationship value) {
        this.join = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the sections property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sections property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSections().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReportLayoutSection }
     * 
     * 
     */
    public List<ReportLayoutSection> getSections() {
        if (sections == null) {
            sections = new ArrayList<ReportLayoutSection>();
        }
        return this.sections;
    }

}
