//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.24 at 12:06:48 PM PDT 
//


package com.salesforce.metadata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SecuritySettings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SecuritySettings">
 *   &lt;complexContent>
 *     &lt;extension base="{}Metadata">
 *       &lt;sequence>
 *         &lt;element name="networkAccess" type="{}NetworkAccess" minOccurs="0"/>
 *         &lt;element name="passwordPolicies" type="{}PasswordPolicies" minOccurs="0"/>
 *         &lt;element name="sessionSettings" type="{}SessionSettings" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SecuritySettings", propOrder = {
    "networkAccess",
    "passwordPolicies",
    "sessionSettings"
})
public class SecuritySettings
    extends Metadata
{

    protected NetworkAccess networkAccess;
    protected PasswordPolicies passwordPolicies;
    protected SessionSettings sessionSettings;

    /**
     * Gets the value of the networkAccess property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkAccess }
     *     
     */
    public NetworkAccess getNetworkAccess() {
        return networkAccess;
    }

    /**
     * Sets the value of the networkAccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkAccess }
     *     
     */
    public void setNetworkAccess(NetworkAccess value) {
        this.networkAccess = value;
    }

    /**
     * Gets the value of the passwordPolicies property.
     * 
     * @return
     *     possible object is
     *     {@link PasswordPolicies }
     *     
     */
    public PasswordPolicies getPasswordPolicies() {
        return passwordPolicies;
    }

    /**
     * Sets the value of the passwordPolicies property.
     * 
     * @param value
     *     allowed object is
     *     {@link PasswordPolicies }
     *     
     */
    public void setPasswordPolicies(PasswordPolicies value) {
        this.passwordPolicies = value;
    }

    /**
     * Gets the value of the sessionSettings property.
     * 
     * @return
     *     possible object is
     *     {@link SessionSettings }
     *     
     */
    public SessionSettings getSessionSettings() {
        return sessionSettings;
    }

    /**
     * Sets the value of the sessionSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link SessionSettings }
     *     
     */
    public void setSessionSettings(SessionSettings value) {
        this.sessionSettings = value;
    }

}
