//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.24 at 12:06:48 PM PDT 
//


package com.salesforce.metadata;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SummaryLayoutStyle.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SummaryLayoutStyle">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Default"/>
 *     &lt;enumeration value="QuoteTemplate"/>
 *     &lt;enumeration value="DefaultQuoteTemplate"/>
 *     &lt;enumeration value="CaseInteraction"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SummaryLayoutStyle")
@XmlEnum
public enum SummaryLayoutStyle {

    @XmlEnumValue("Default")
    DEFAULT("Default"),
    @XmlEnumValue("QuoteTemplate")
    QUOTE_TEMPLATE("QuoteTemplate"),
    @XmlEnumValue("DefaultQuoteTemplate")
    DEFAULT_QUOTE_TEMPLATE("DefaultQuoteTemplate"),
    @XmlEnumValue("CaseInteraction")
    CASE_INTERACTION("CaseInteraction");
    private final String value;

    SummaryLayoutStyle(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SummaryLayoutStyle fromValue(String v) {
        for (SummaryLayoutStyle c: SummaryLayoutStyle.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
