//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.24 at 12:06:48 PM PDT 
//


package com.salesforce.metadata;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WorkflowTriggerTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="WorkflowTriggerTypes">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="onCreateOnly"/>
 *     &lt;enumeration value="onCreateOrTriggeringUpdate"/>
 *     &lt;enumeration value="onAllChanges"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "WorkflowTriggerTypes")
@XmlEnum
public enum WorkflowTriggerTypes {

    @XmlEnumValue("onCreateOnly")
    ON_CREATE_ONLY("onCreateOnly"),
    @XmlEnumValue("onCreateOrTriggeringUpdate")
    ON_CREATE_OR_TRIGGERING_UPDATE("onCreateOrTriggeringUpdate"),
    @XmlEnumValue("onAllChanges")
    ON_ALL_CHANGES("onAllChanges");
    private final String value;

    WorkflowTriggerTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static WorkflowTriggerTypes fromValue(String v) {
        for (WorkflowTriggerTypes c: WorkflowTriggerTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
